import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "FAQ — Frequently Asked Questions",
  description:
    "Frequently asked questions about PSX Stock Analyzer — a free tool that analyzes Pakistan Stock Exchange stocks in plain English for beginner investors. Learn about features, data sources, Shariah compliance, and more.",
  alternates: { canonical: "https://psxstocksanalyzer.com/faq" },
};

const FAQS: { q: string; a: string }[] = [
  {
    q: "What is PSX Stock Analyzer?",
    a: "PSX Stock Analyzer is a free online tool that analyzes Pakistan Stock Exchange (PSX) listed companies and explains the results in plain English for beginner investors. It covers P/E ratio, dividends, Shariah compliance, financials, and gives a plain-language verdict — no finance degree needed.",
  },
  {
    q: "Is PSX Stock Analyzer free to use?",
    a: "Yes, completely free. No sign-up, no subscription, no hidden fees. Simply search for any PSX-listed company and get instant analysis.",
  },
  {
    q: "What is the Pakistan Stock Exchange (PSX)?",
    a: "PSX is the national stock exchange of Pakistan, located in Karachi. It lists over 500 companies across sectors like banking, cement, oil & gas, fertilizer, and technology. The KSE-100 index tracks the top 100 companies by market capitalization.",
  },
  {
    q: "How do I analyze a PSX stock?",
    a: "Go to psxstocksanalyzer.com, paste a PSX company URL (for example, https://dps.psx.com.pk/company/LUCK for Lucky Cement), and click Analyze. You'll get a complete breakdown of the company's financials, valuation, dividends, risk level, and a plain-English verdict.",
  },
  {
    q: "Can I compare two PSX stocks?",
    a: "Yes! Switch to the Compare tab, enter two PSX company URLs, and get a side-by-side comparison across 7 key metrics — P/E ratio, profit margin, EPS growth, dividend yield, market cap, revenue growth, and risk level. The tool declares an overall winner with an explanation.",
  },
  {
    q: "Do I need a finance degree to understand the analysis?",
    a: "Not at all. PSX Stock Analyzer is built specifically for beginners. Every metric is explained in plain English. We translate complex financial jargon into simple, easy-to-understand language. There's also a glossary with a Roman Urdu toggle.",
  },
  {
    q: "Where does the stock data come from?",
    a: "Stock prices and company data come directly from the PSX Data Portal (dps.psx.com.pk). Financial statements (Income Statement, Balance Sheet, Cash Flow) are sourced from Yahoo Finance. Shariah compliance is checked against the KMI All Shares index.",
  },
  {
    q: "How often is the data updated?",
    a: "Stock prices and trading data are fetched live from PSX each time you analyze a stock. Financial statements update quarterly or annually based on company filings. The stock list is cached for 1 hour.",
  },
  {
    q: "What does Shariah Compliant mean?",
    a: "Stocks that meet Islamic finance screening criteria are part of the KMI (KSE Meezan Index) All Shares index. PSX screens companies based on their business activities and financial ratios against Shariah guidelines. PSX Stock Analyzer shows a green Shariah Compliant badge on qualifying stocks.",
  },
  {
    q: "Is this financial advice?",
    a: "No. PSX Stock Analyzer is for educational purposes only. It provides data and analysis to help you understand PSX stocks, but you should always do your own research and consult a qualified financial advisor before investing in the stock market.",
  },
  {
    q: "What metrics does the analysis cover?",
    a: "The analysis includes: current stock price, 52-week high/low range, P/E ratio, profit margin, EPS growth, dividend history and yield, revenue and profit trends, market capitalization, buyer/seller strength, circuit breaker limits, Shariah compliance status, risk level, and a final verdict in plain English.",
  },
  {
    q: "Does PSX Stock Analyzer use AI?",
    a: "No. All analysis is generated by rule-based algorithms that evaluate financial data from official sources. There are no AI or LLM calls involved. The verdicts are based on established financial metrics and thresholds.",
  },
  {
    q: "What stocks can I analyze?",
    a: "You can analyze any company listed on the Pakistan Stock Exchange (PSX). This includes all KSE-100, KSE-30, and KMI All Shares index constituents, as well as other listed companies. PSX Stock Analyzer does not cover international markets.",
  },
  {
    q: "What is the KSE-100 index?",
    a: "The KSE-100 (Karachi Stock Exchange 100) index is the benchmark stock market index of the Pakistan Stock Exchange. It tracks the top 100 companies by market capitalization and is the most widely followed indicator of Pakistan's stock market performance.",
  },
  {
    q: "How is the risk level calculated?",
    a: "The risk level (Low, Medium, or High) is determined by evaluating multiple factors including P/E ratio, profit margin trends, EPS growth consistency, dividend history, and price volatility. The assessment uses rule-based thresholds — not subjective judgment.",
  },
  {
    q: "What formulas does the tool explain?",
    a: "The educational formulas section explains: Book Value per Share, Dividend Yield, P/E Ratio (Price-to-Earnings), Earnings Per Share (EPS), Market Capitalization, and Profit Margin — each with the formula and a plain-English explanation of what it means.",
  },
  {
    q: "What is the difference between KSE-100 and KSE-30?",
    a: "The KSE-100 tracks the top 100 companies on PSX by free-float market capitalization and is the main benchmark index. The KSE-30 is a narrower index of the 30 most liquid and large companies — it is price-weighted based on free-float shares and designed for tracking market leaders only. Full methodology is published by PSX (psx.com.pk).",
  },
  {
    q: "What are PSX trading hours?",
    a: "The Pakistan Stock Exchange is open from 9:30 AM to 3:30 PM Pakistan Standard Time, Monday to Friday. There is a pre-open session before the main trading starts. The market is closed on weekends and on national holidays announced by PSX (psx.com.pk).",
  },
  {
    q: "How much money do I need to start investing in PSX?",
    a: "There is no fixed minimum. Many brokers accept accounts opened with as little as PKR 1,000–5,000, and shares of some PSX-listed companies trade for less than PKR 50. Start small while you learn, and only invest money you can afford to leave untouched for the long term.",
  },
  {
    q: "Who regulates the Pakistan Stock Exchange?",
    a: "PSX is regulated by the Securities and Exchange Commission of Pakistan (SECP), which is the statutory regulator for capital markets, corporate sector, and non-bank financial institutions in Pakistan. SECP rules are published at secp.gov.pk.",
  },
  {
    q: "What is a CDC sub-account?",
    a: "A CDC sub-account is an electronic account that holds your PSX shares in your name at the Central Depository Company (CDC). It is opened by your broker on your behalf. The CDC sub-account keeps your shares safe and separate from the broker's own assets. More info at cdcpakistan.com.",
  },
  {
    q: "What is NCCPL?",
    a: "NCCPL stands for the National Clearing Company of Pakistan Limited. It is the central clearing and settlement company for PSX trades. When you buy or sell a share, NCCPL makes sure the money goes to the seller and the shares go to the buyer. See nccpl.com.pk for details.",
  },
  {
    q: "Is the Pakistan Stock Exchange safe to invest in?",
    a: "PSX is a regulated market under SECP, and investor protections include CDC sub-accounts and the NCCPL clearing system. However, share prices can go up or down, and individual stocks can lose value. 'Safe' depends on which company you buy, how much research you do, and how long you hold. Never invest money you cannot afford to lose.",
  },
  {
    q: "What are circuit breakers on PSX?",
    a: "Circuit breakers are daily price limits that stop a stock from moving too far up or down in a single trading session. When a stock hits the upper or lower circuit, trading in that stock pauses. The limits are designed to prevent extreme volatility. The exact percentage is set and published by PSX.",
  },
  {
    q: "What is a dividend?",
    a: "A dividend is a portion of a company's profit paid to its shareholders. On PSX, dividends are announced by the company's board and usually paid in cash (per share). Not every company pays a dividend — some reinvest all profits into growth instead.",
  },
  {
    q: "What is Earnings Per Share (EPS)?",
    a: "EPS is the company's profit after tax divided by the total number of shares outstanding. For example, if a company makes PKR 1 billion profit and has 100 million shares, EPS = PKR 10. Higher EPS means each share is earning more profit for its owner.",
  },
  {
    q: "How do I check a PSX company's annual report?",
    a: "Every PSX-listed company is required to publish an annual report. You can find them on the company's official website under 'Investor Relations', or on the PSX Data Portal at dps.psx.com.pk under the company's profile. Annual reports contain the audited financial statements, director's report, and detailed financial notes.",
  },
  {
    q: "What is LDCP?",
    a: "LDCP stands for Last Day Close Price. It is the official closing price of a share on the previous trading day. PSX uses LDCP as the reference for calculating the next day's upper and lower circuit breaker limits.",
  },
  {
    q: "How is capital gains tax calculated on PSX shares?",
    a: "Capital Gains Tax (CGT) is charged on profits when you sell shares. The rates depend on how long you held the share and are set by the Federal Board of Revenue (FBR) through the annual Federal Budget. NCCPL collects CGT automatically on your behalf. Always check the current year's rates at fbr.gov.pk before filing your taxes.",
  },
  {
    q: "Can non-Pakistanis invest in the Pakistan Stock Exchange?",
    a: "Yes. Non-residents and foreign investors can invest in PSX by opening a Special Convertible Rupee Account (SCRA) with a local bank, along with a CDC sub-account via a registered broker. The framework is set by the State Bank of Pakistan (sbp.org.pk) and SECP.",
  },
  {
    q: "What is a bonus share?",
    a: "A bonus share is a free additional share given to existing shareholders in proportion to the shares they already own. For example, a 10% bonus issue means you get 1 free share for every 10 shares you hold. Bonus shares do not add new money to the company — they are a way of distributing accumulated profit in the form of extra shares.",
  },
  {
    q: "What is the difference between bonus shares and right shares?",
    a: "Bonus shares are free — given to shareholders out of retained earnings. Right shares are new shares offered to existing shareholders at a discounted price, and you have to pay to buy them. Right issues raise fresh capital for the company, while bonus issues do not.",
  },
  {
    q: "Can I lose all my money in the Pakistan Stock Exchange?",
    a: "Yes. If you invest in a single company and it goes bankrupt or its shares become worthless, you can lose your entire investment in that stock. This risk is reduced by spreading your money across several companies and sectors (called diversification), and by investing only what you can afford to hold for the long term.",
  },
];

// FAQ page schema (page-level, separate from global FAQ in layout.tsx)
const faqPageSchema = {
  "@context": "https://schema.org",
  "@type": "FAQPage",
  mainEntity: FAQS.map((faq) => ({
    "@type": "Question",
    name: faq.q,
    acceptedAnswer: {
      "@type": "Answer",
      text: faq.a,
    },
  })),
};

export default function FAQPage() {
  return (
    <div className="min-h-screen bg-[#F8F3EA]">
      {/* JSON-LD for FAQ page — placed in body (valid per schema.org spec) */}
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify(faqPageSchema),
        }}
      />

      <main className="max-w-3xl mx-auto px-4 py-10">
        <div className="bg-white rounded-xl border border-[#E5E0D9] p-8 space-y-8">
          <div>
            <h1 className="text-2xl font-bold text-[#404E3F]">Frequently Asked Questions</h1>
            <p className="text-sm text-[#404E3F]/60 mt-2 leading-relaxed">
              PSX Stock Analyzer is a free stock analysis tool for the Pakistan Stock Exchange (PSX) that explains stocks in plain English for beginner Pakistani investors. Find answers to common questions below.
            </p>
          </div>

          <div className="space-y-6">
            {FAQS.map((faq, i) => (
              <section key={i} className="border-b border-[#E5E0D9] pb-5 last:border-0 last:pb-0">
                <h2 className="text-sm font-semibold text-[#404E3F] mb-2">{faq.q}</h2>
                <p className="text-sm text-[#404E3F]/70 leading-relaxed">{faq.a}</p>
              </section>
            ))}
          </div>

          <div className="p-4 rounded-xl bg-[#4BC232]/10 border border-[#4BC232]/20">
            <p className="text-sm text-[#404E3F] text-center leading-relaxed">
              Still have questions?{" "}
              <Link href="/contact" className="text-[#2B5288] underline font-medium">Contact us</Link>
              {" "}or start analyzing stocks on the{" "}
              <Link href="/" className="text-[#2B5288] underline font-medium">homepage</Link>.
            </p>
          </div>
        </div>
      </main>

    </div>
  );
}
