import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "FAQ — Frequently Asked Questions",
  description:
    "Frequently asked questions about PSX Stock Analyzer — a free tool that analyzes Pakistan Stock Exchange stocks in plain English for beginner investors. Learn about features, data sources, Shariah compliance, and more.",
  alternates: { canonical: "https://psxstocksanalyzer.com/faq" },
};

const FAQS: { q: string; a: string }[] = [
  {
    q: "What is PSX Stock Analyzer?",
    a: "PSX Stock Analyzer is a free online tool that analyzes Pakistan Stock Exchange (PSX) listed companies and explains the results in plain English for beginner investors. It covers P/E ratio, dividends, Shariah compliance, financials, and gives a plain-language verdict — no finance degree needed.",
  },
  {
    q: "Is PSX Stock Analyzer free to use?",
    a: "Yes, completely free. No sign-up, no subscription, no hidden fees. Simply search for any PSX-listed company and get instant analysis.",
  },
  {
    q: "What is the Pakistan Stock Exchange (PSX)?",
    a: "PSX is the national stock exchange of Pakistan, located in Karachi. It lists over 500 companies across sectors like banking, cement, oil & gas, fertilizer, and technology. The KSE-100 index tracks the top 100 companies by market capitalization.",
  },
  {
    q: "How do I analyze a PSX stock?",
    a: "Go to psxstocksanalyzer.com, paste a PSX company URL (for example, https://dps.psx.com.pk/company/LUCK for Lucky Cement), and click Analyze. You'll get a complete breakdown of the company's financials, valuation, dividends, risk level, and a plain-English verdict.",
  },
  {
    q: "Can I compare two PSX stocks?",
    a: "Yes! Switch to the Compare tab, enter two PSX company URLs, and get a side-by-side comparison across 7 key metrics — P/E ratio, profit margin, EPS growth, dividend yield, market cap, revenue growth, and risk level. The tool declares an overall winner with an explanation.",
  },
  {
    q: "Do I need a finance degree to understand the analysis?",
    a: "Not at all. PSX Stock Analyzer is built specifically for beginners. Every metric is explained in plain English. We translate complex financial jargon into simple, easy-to-understand language. There's also a glossary with a Roman Urdu toggle.",
  },
  {
    q: "Where does the stock data come from?",
    a: "Stock prices and company data come directly from the PSX Data Portal (dps.psx.com.pk). Financial statements (Income Statement, Balance Sheet, Cash Flow) are sourced from Yahoo Finance. Shariah compliance is checked against the KMI All Shares index.",
  },
  {
    q: "How often is the data updated?",
    a: "Stock prices and trading data are fetched live from PSX each time you analyze a stock. Financial statements update quarterly or annually based on company filings. The stock list is cached for 1 hour.",
  },
  {
    q: "What does Shariah Compliant mean?",
    a: "Stocks that meet Islamic finance screening criteria are part of the KMI (KSE Meezan Index) All Shares index. PSX screens companies based on their business activities and financial ratios against Shariah guidelines. PSX Stock Analyzer shows a green Shariah Compliant badge on qualifying stocks.",
  },
  {
    q: "Is this financial advice?",
    a: "No. PSX Stock Analyzer is for educational purposes only. It provides data and analysis to help you understand PSX stocks, but you should always do your own research and consult a qualified financial advisor before investing in the stock market.",
  },
  {
    q: "What metrics does the analysis cover?",
    a: "The analysis includes: current stock price, 52-week high/low range, P/E ratio, profit margin, EPS growth, dividend history and yield, revenue and profit trends, market capitalization, buyer/seller strength, circuit breaker limits, Shariah compliance status, risk level, and a final verdict in plain English.",
  },
  {
    q: "Does PSX Stock Analyzer use AI?",
    a: "No. All analysis is generated by rule-based algorithms that evaluate financial data from official sources. There are no AI or LLM calls involved. The verdicts are based on established financial metrics and thresholds.",
  },
  {
    q: "What stocks can I analyze?",
    a: "You can analyze any company listed on the Pakistan Stock Exchange (PSX). This includes all KSE-100, KSE-30, and KMI All Shares index constituents, as well as other listed companies. PSX Stock Analyzer does not cover international markets.",
  },
  {
    q: "What is the KSE-100 index?",
    a: "The KSE-100 (Karachi Stock Exchange 100) index is the benchmark stock market index of the Pakistan Stock Exchange. It tracks the top 100 companies by market capitalization and is the most widely followed indicator of Pakistan's stock market performance.",
  },
  {
    q: "How is the risk level calculated?",
    a: "The risk level (Low, Medium, or High) is determined by evaluating multiple factors including P/E ratio, profit margin trends, EPS growth consistency, dividend history, and price volatility. The assessment uses rule-based thresholds — not subjective judgment.",
  },
  {
    q: "What formulas does the tool explain?",
    a: "The educational formulas section explains: Book Value per Share, Dividend Yield, P/E Ratio (Price-to-Earnings), Earnings Per Share (EPS), Market Capitalization, and Profit Margin — each with the formula and a plain-English explanation of what it means.",
  },
];

// FAQ page schema (page-level, separate from global FAQ in layout.tsx)
const faqPageSchema = {
  "@context": "https://schema.org",
  "@type": "FAQPage",
  mainEntity: FAQS.map((faq) => ({
    "@type": "Question",
    name: faq.q,
    acceptedAnswer: {
      "@type": "Answer",
      text: faq.a,
    },
  })),
};

export default function FAQPage() {
  return (
    <div className="min-h-screen bg-[#F8F3EA]">
      <head>
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify(faqPageSchema),
          }}
        />
      </head>

      <header className="bg-white border-b border-[#E5E0D9] py-4">
        <div className="max-w-3xl mx-auto px-4">
          <Link href="/" className="text-lg font-bold text-[#404E3F] hover:text-[#4BC232] transition-colors">
            PSX Stock Analyzer
          </Link>
        </div>
      </header>

      <main className="max-w-3xl mx-auto px-4 py-10">
        <div className="bg-white rounded-xl border border-[#E5E0D9] p-8 space-y-8">
          <div>
            <h1 className="text-2xl font-bold text-[#404E3F]">Frequently Asked Questions</h1>
            <p className="text-sm text-[#404E3F]/60 mt-2 leading-relaxed">
              PSX Stock Analyzer is a free stock analysis tool for the Pakistan Stock Exchange (PSX) that explains stocks in plain English for beginner Pakistani investors. Find answers to common questions below.
            </p>
          </div>

          <div className="space-y-6">
            {FAQS.map((faq, i) => (
              <section key={i} className="border-b border-[#E5E0D9] pb-5 last:border-0 last:pb-0">
                <h2 className="text-sm font-semibold text-[#404E3F] mb-2">{faq.q}</h2>
                <p className="text-sm text-[#404E3F]/70 leading-relaxed">{faq.a}</p>
              </section>
            ))}
          </div>

          <div className="p-4 rounded-xl bg-[#4BC232]/10 border border-[#4BC232]/20">
            <p className="text-sm text-[#404E3F] text-center leading-relaxed">
              Still have questions?{" "}
              <Link href="/contact" className="text-[#2B5288] underline font-medium">Contact us</Link>
              {" "}or start analyzing stocks on the{" "}
              <Link href="/" className="text-[#2B5288] underline font-medium">homepage</Link>.
            </p>
          </div>
        </div>
      </main>

      <footer className="border-t border-[#E5E0D9] mt-16 py-6">
        <div className="max-w-3xl mx-auto px-4 text-center space-y-2">
          <p className="text-xs text-[#404E3F]/40">
            For educational purposes only. Not financial advice.
          </p>
          <div className="flex flex-wrap justify-center gap-x-4 gap-y-1">
            <Link href="/privacy" className="text-xs text-[#2B5288] hover:underline">Privacy Policy</Link>
            <Link href="/terms" className="text-xs text-[#2B5288] hover:underline">Terms of Service</Link>
            <Link href="/about" className="text-xs text-[#2B5288] hover:underline">About</Link>
            <Link href="/contact" className="text-xs text-[#2B5288] hover:underline">Contact</Link>
          </div>
        </div>
      </footer>
    </div>
  );
}
