import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Service",
  description:
    "Terms of Service for PSX Stock Analyzer. Read our terms and conditions for using the free stock analysis tool.",
  alternates: { canonical: "https://psxstocksanalyzer.com/terms" },
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-brand-bg">
      <main className="max-w-3xl mx-auto px-4 py-10">
        <div className="bg-brand-card rounded-xl border border-brand-border p-8 space-y-6">
          <div>
            <h1 className="text-2xl font-bold text-brand-fg">Terms of Service</h1>
            <p className="text-sm text-brand-fg/50 mt-1">Last updated: March 2026</p>
          </div>

          <Section title="Acceptance of Terms">
            PSX Stock Analyzer is a free stock analysis tool for the Pakistan Stock Exchange (PSX) that
            explains stocks in plain English for beginner Pakistani investors. By accessing and using
            PSX Stock Analyzer (psxstocksanalyzer.com), you agree to be bound by these Terms of Service.
            If you do not agree, please do not use the website.
          </Section>

          <Section title="Not Financial Advice">
            <strong>PSX Stock Analyzer is an educational tool only.</strong> The information provided
            on this website does not constitute financial advice, investment advice, trading advice,
            or any other form of professional advice. The analysis, verdicts, ratings, and
            recommendations displayed are generated by automated rule-based algorithms — not by
            financial advisors or AI.
            <br /><br />
            You should always conduct your own research and consult a qualified financial advisor
            before making any investment decisions. Investing in the stock market carries inherent
            risks, and past performance does not guarantee future results.
          </Section>

          <Section title="Data Accuracy">
            Stock prices, company data, and financial information are sourced from the PSX Data Portal
            (dps.psx.com.pk) and Yahoo Finance. While we strive to provide accurate and up-to-date
            information, we do not guarantee the accuracy, completeness, or timeliness of any data
            displayed on this website.
            <br /><br />
            Data may be delayed, incomplete, or contain errors due to the nature of third-party data
            sources. Numbers may differ from official company filings due to rounding, data timing,
            or source discrepancies.
          </Section>

          <Section title="No Warranties">
            This website is provided &quot;as is&quot; and &quot;as available&quot; without any warranties of any kind,
            either express or implied, including but not limited to warranties of merchantability,
            fitness for a particular purpose, or non-infringement.
          </Section>

          <Section title="Limitation of Liability">
            In no event shall PSX Stock Analyzer, its creators, or contributors be liable for any
            direct, indirect, incidental, special, or consequential damages arising from your use
            of this website or reliance on any information provided herein. This includes, but is
            not limited to, any financial losses resulting from investment decisions.
          </Section>

          <Section title="Third-Party Services">
            Our website relies on third-party services including the PSX Data Portal, Yahoo Finance,
            Google AdSense, and Vercel. We are not responsible for the availability, accuracy, or
            policies of these third-party services.
          </Section>

          <Section title="Modifications">
            We reserve the right to modify, suspend, or discontinue the website or any part of it
            at any time without prior notice. We also reserve the right to update these Terms of
            Service at any time. Continued use of the website after changes constitutes acceptance
            of the modified terms.
          </Section>

          <Section title="Intellectual Property">
            The PSX Stock Analyzer name, logo, design, and original content are the property of the
            website creators. Stock data and financial information belong to their respective sources
            (PSX, Yahoo Finance).
          </Section>

          <Section title="Governing Law">
            These terms shall be governed by and construed in accordance with the laws of Pakistan.
            Any disputes arising from the use of this website shall be subject to the jurisdiction
            of the courts of Pakistan.
          </Section>

          <Section title="Contact">
            If you have questions about these Terms, please visit our{" "}
            <Link href="/contact" className="text-[#2B5288] underline">Contact page</Link>.
          </Section>
        </div>
      </main>

    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div>
      <h2 className="text-base font-semibold text-brand-fg mb-2">{title}</h2>
      <p className="text-sm text-brand-fg/70 leading-relaxed">{children}</p>
    </div>
  );
}
